# Generated by Django 2.0.1 on 2018-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180701_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='the_answer',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
